#!/bin/bash
# Copyright (C) 2000-2016 Synology Inc. All rights reserved.

case ${MakeClean} in
	[Yy][Ee][Ss])
		make clean
		;;
esac

# You can use CC CFLAGS LD LDFLAGS CXX CXXFLAGS AR RANLIB READELF STRIP here
#echo "${CC} ${CFLAGS} source/smi-server.c -o smi.server"
#${CC} ${CFLAGS} source/smi-server.c -o smi-server
#all:	 source/swb-serial.c source/smi-serial.c source/smi-server.c source/webserver.c
${CC} ${CFLAGS} -o smi-server source/swb-serial.c source/smi-serial.c source/smi-server.c source/webserver.c


# Or you can use Makefile to genarate executable.
#echo "make ${MAKE_FLAGS}"
#make ${MAKE_FLAGS}
