#!/bin/sh

### This script will be executed when package installed and upgraded.
### Actions after package installed.
### ex. create database, create symbolic link...

ln -sf $SYNOPKG_PKGDEST/usr/bin/smi-server /usr/bin/
cp $SYNOPKG_PKGDEST/smi-server.sc /var/packages/smi-server/smi-server.sc
sudo echo ",\"port-config\":{\"protocol-file\":\"smi-server.sc\"}" >> /var/packages/smi-server/conf/resource
sudo /usr/syno/sbin/synopkghelper update smi-server port-config

exit 0
