#!/bin/sh

### This script will be executed when package uninstalled and upgraded.
### Actions after package uninstalled.
### ex. remove garbage files.

rm -f /usr/bin/smi-server
cp $SYNOPKG_PKGDEST/smi-server.sc /usr/local/etc/services.d/smi-server.sc

exit 0
