#!/bin/sh
PATH=/bin:/usr/bin
. `dirname $0`/installer
`basename $0` > $SYNOPKG_TEMP_LOGFILE

### This script will be executed when package uninstalled and upgraded.
### Actions after package uninstalled.
### ex. remove garbage files.

# rm -f /usr/bin/smi-server
# rm -f /usr/local/etc/services.d/smi-server.sc
#
# exit 0
