#!/bin/sh

### This script will be executed when package installed and upgraded.
### Actions after package installed.
### ex. create database, create symbolic link...

ln -sf $SYNOPKG_PKGDEST/usr/bin/smi-server /usr/bin/
cp $SYNOPKG_PKGDEST/smi-server.sc /usr/local/etc/services.d/
#echo {{pkgwizard_smi_server_port}} >> /var/packages/smi-server/port
echo ${pkgwizard_smi_server_port} >> /var/packages/smi-server/postport
echo ",\"port-config\":{\"protocol-file\":\"smi-server.sc\"}${pkgwizard_smi_server_port}" >> /var/packages/smi-server/conf/resource
/usr/syno/sbin/synopkghelper update smi-server port-config

exit 0
