#!/bin/sh

### This script will be executed when package installed and upgraded.
### Actions after package installed.
### ex. create database, create symbolic link...

ln -sf $SYNOPKG_PKGDEST/usr/bin/smi-server /usr/bin/
echo "[smi-server]" >>$SYNOPKG_PKGDEST/smi-server.sc.new
echo "title=\"SMI-Server\"" >>$SYNOPKG_PKGDEST/smi-server.sc.new
echo "desc=\"SMI-Server\"" >>$SYNOPKG_PKGDEST/smi-server.sc.new
echo "port_forward=\"no\"" >>$SYNOPKG_PKGDEST/smi-server.sc.new
echo "dst.ports=\"${pkgwizard_smi_server_port}/tcp\"" >>$SYNOPKG_PKGDEST/smi-server.sc.new
#### copy and rename services-configuration-file
cp $SYNOPKG_PKGDEST/smi-server.sc.new /usr/local/etc/services.d/smi-server.sc

echo ${pkgwizard_smi_server_port} >> /var/packages/smi-server/port      # config file ?!

### add port config to resource file
echo ",\"port-config\":{" >> /var/packages/smi-server/conf/resource
echo "\"protocol-file\":\"smi-server.sc\"}" >> /var/packages/smi-server/conf/resource

### add syslog infos to resource file
echo ",\"syslog-config\":{" >> /var/packages/smi-server/conf/resource
echo "\"patterndb-relpath\":\"smi-server.conf\"}" >> /var/packages/smi-server/conf/resource

/usr/syno/sbin/synopkghelper update smi-server port-config

exit 0
