#!/bin/sh
PATH=/bin:/usr/bin
. `dirname $0`/installer
`basename $0` > $SYNOPKG_TEMP_LOGFILE

### This script will be execute when package installed and upgraded.
### Actions before package installed.
### ex. check environment.

# Create the shared folder with SMI-Config

#synoshare {--add} sharename share_desc share_path user_list_na user_list_rw user_list_ro share_browsable adv_privilege
#synoshare --add "SMI" "Freigabe des SMI-Server" "/volume1/SMI" "" "root, admin" "" 1 ""
# mkdir -p /var/packages/smi-server/conf/
# echo "$SYNOPKG_PKGDEST_VOL/SMI" >> /var/packages/smi-server/conf/share
# echo "${SYNOPKG_PKGDEST_VOL}/SMI" >> /var/packages/smi-server/conf/share
# echo $SYNOPKG_PKGDEST_VOL >> /var/packages/smi-server/conf/share
# echo ${SYNOPKG_PKGDEST_VOL} >> /var/packages/smi-server/conf/share
# sudo /usr/syno/sbin/synoshare --add "SmiPre" "SMI-Server shared folder" "/volume1/SmiPre" "" "admin" "" 1 ""
# echo "--------------------------------" >> /var/packages/smi-server/conf/share
# if [ $? != 0 ]; then
# 	echo "${illegal_share_name}" >> $SYNOPKG_TEMP_LOGFILE
# 	exit 1
# fi

# exit 0
