#!/bin/sh
PATH=/bin:/usr/bin
. `dirname $0`/installer
`basename $0` > $SYNOPKG_TEMP_LOGFILE

# ### This script will execute ONLY when package upgraded.
# ### Actions before package upgraded.
# ### ex. backup user settings for package upgrade.
#
# exit 0
